Repository kevin-lee/sbt-github-pages, pull requests merged in 2021-07, with the labels that each got.

#102 Add default values for org/repo names extracted from `git remote` info
  src/main/scala/githubpages/GitHubPagesKeys.scala
  src/main/scala/githubpages/GitHubPagesPlugin.scala
  website/docs/config.md
Labels: pr

#103 sbt-github-pages v0.6.0
  changelogs/0.6.0.md
Labels: pr, release

#104 Updated: docs with the new release info
  website/docs/examples.md
  website/docs/getting-started.md
Labels: documentation, pr, publish-docs, release

#105 Upgraded sbt plugins
  project/plugins.sbt
Labels: pr
